### PR TITLE
T

### PR DESCRIPTION
**Pull request by xiaojjk11**

### CODE REVIEW

**Comment by xiaojjk11** [comment]
ID:0xcbd484c82661c21a5bfab1c03dcae63f8363fbbd1e1c019dd8c472b722a04d1a

**Comment by MedovTimur** [comment]
What happened to the tests? 
why is the file called `basic` and not `basic.rs`?

**Comment by xiaojjk11** [comment]
> What happened to the tests? why is the file called `basic` and not `basic.rs`?

Because of this error in my test code, I am unable to initialize the test program. I hope you can help me check the test program or see if there is any logical error. I have renamed the local error file and basic to basic.rs, and I hope you can help me find the mistake.
Thank you for taking the time to help me, I really appreciate it!

**Comment by xiaojjk11** [comment]
> What happened to the tests? why is the file called `basic` and not `basic.rs`?

I've uploaded the picture.

**Comment by MedovTimur** [comment]
You use `send_bytes` function, which is needed to send bytes (vector of bytes), but as an argument you pass a certain type instead of bytes. 
solution: change all `send_bytes` to simple `send`

**Comment by xiaojjk11** [comment]
> You use `send_bytes` function, which is needed to send bytes (vector of bytes), but as an argument you pass a certain type instead of bytes. solution: change all `send_bytes` to simple `send`

I received your modification suggestions. My new test code uses send to send messages, and it has successfully passed the tests. Thank you!

**Comment by xiaojjk11** [comment]
> You use `send_bytes` function, which is needed to send bytes (vector of bytes), but as an argument you pass a certain type instead of bytes. solution: change all `send_bytes` to simple `send`

Why have all my intermediate courses been approved, but my basic course hasn’t been reviewed yet? Also, the tokens I claimed for my intermediate courses haven’t arrived in my wallet yet.

**Pull request merged**
